-- ================================================================
-- Auth Service — Database Schema (PostgreSQL 13+)
-- ================================================================
-- Owns: "user", role, user_role, refresh_token
--
-- Roles are seeded with ROLE_USER, ROLE_ADMIN, ROLE_THEATRE_OWNER.
-- Every new user gets ROLE_USER by default at the application level.
-- ================================================================

CREATE TABLE "user" (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    full_name       VARCHAR(200)    NOT NULL,
    phone           VARCHAR(20),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT now()
);

CREATE TABLE role (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_role (
    user_id     UUID    NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role_id     INT     NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE refresh_token (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id         UUID            NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    token           TEXT            NOT NULL UNIQUE,
    expires_at      TIMESTAMP       NOT NULL,
    revoked         BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT now()
);

-- ── Indexes ────────────────────────────────────────────────

CREATE INDEX idx_user_email             ON "user"(email);
CREATE INDEX idx_refresh_token_user     ON refresh_token(user_id);
CREATE INDEX idx_refresh_token_token    ON refresh_token(token);

-- ── Seed Roles ─────────────────────────────────────────────

INSERT INTO role (name) VALUES
    ('ROLE_USER'),
    ('ROLE_ADMIN'),
    ('ROLE_THEATRE_OWNER');
