spring:
  application:
    name: booking
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookmyshow}
    username: ${DB_USERNAME:catalog}
    password: ${DB_PASSWORD:catalog}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      #enables transactional in kafka - to ensure exactly-once semantics (EOS).
      #transaction-id-prefix: tx-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8082
  servlet:
    context-path: /booking/v1

  error:
    include-message: always

booking:
  seat-hold-minutes: 10

jwt:
  public-key: classpath:keys/auth-public.pem

inventory:
  base-url: http://localhost:8081/inventory/v1

auth:
  base-url: http://localhost:8083/auth/v1
