{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  {{- if .Values.database.enabled }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
