-- ================================================================
-- Inventory Service — Database Schema (PostgreSQL 13+)
-- ================================================================
-- Owns: city, language, format, movie, movie_language_format,
--       theatre, screen, seat, show, show_seat
--
-- ID strategy:
--   UUID → user-facing entities (movie, theatre, screen, seat, show)
--   INT  → internal lookups    (city, language, format)
-- ================================================================

CREATE TYPE seat_status AS ENUM ('AVAILABLE', 'BOOKED', 'BLOCKED');

-- ── Lookup tables ──────────────────────────────────────────

CREATE TABLE city (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100)  NOT NULL,
    state     VARCHAR(100)  NOT NULL,
    country   VARCHAR(100)  NOT NULL DEFAULT 'India',
    latitude  DECIMAL(9,6),
    longitude DECIMAL(9,6)
);

CREATE TABLE language (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL UNIQUE,
    code    CHAR(5)      NOT NULL UNIQUE
);

CREATE TABLE format (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL UNIQUE
);

-- ── Core entities ──────────────────────────────────────────

CREATE TABLE movie (
    id              UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
    title           VARCHAR(300)  NOT NULL,
    description     TEXT,
    duration_min    INT           NOT NULL,
    genre           VARCHAR(100),
    rating          INT           DEFAULT 0 CHECK (rating BETWEEN 0 AND 100),
    release_date    DATE          NOT NULL,
    poster_url      VARCHAR(500),
    director        VARCHAR(200),
    trailer_url     VARCHAR(500),
    cast_csv        TEXT
);

CREATE TABLE movie_language_format (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    movie_id    UUID NOT NULL REFERENCES movie(id),
    language_id INT  NOT NULL REFERENCES language(id),
    format_id   INT  NOT NULL REFERENCES format(id),
    UNIQUE (movie_id, language_id, format_id)
);

CREATE TABLE theatre (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    address     TEXT,
    city_id     INT NOT NULL REFERENCES city(id),
    latitude    DECIMAL(9,6),
    longitude   DECIMAL(9,6),
    owner_id    UUID NOT NULL
);

CREATE INDEX idx_theatre_owner ON theatre(owner_id);

CREATE TABLE screen (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    theatre_id  UUID        NOT NULL REFERENCES theatre(id),
    format_id   INT         NOT NULL REFERENCES format(id),
    total_seats INT         NOT NULL
);

CREATE TABLE seat (
    id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    screen_id   UUID        NOT NULL REFERENCES screen(id),
    row_label   CHAR(2)     NOT NULL,
    seat_number INT         NOT NULL,
    UNIQUE (screen_id, row_label, seat_number)
);

CREATE TABLE show (
    id              UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
    mlf_id          UUID          NOT NULL REFERENCES movie_language_format(id),
    screen_id       UUID          NOT NULL REFERENCES screen(id),
    start_time      TIMESTAMP     NOT NULL,
    end_time        TIMESTAMP     NOT NULL,
    price           DECIMAL(10,2) NOT NULL
);

CREATE TABLE show_seat (
    id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    show_id     UUID        NOT NULL REFERENCES show(id),
    seat_id     UUID        NOT NULL REFERENCES seat(id),
    status      seat_status NOT NULL DEFAULT 'AVAILABLE',
    UNIQUE (show_id, seat_id)
);

-- ── Indexes ────────────────────────────────────────────────

CREATE INDEX idx_show_mlf       ON show(mlf_id, start_time);
CREATE INDEX idx_show_screen    ON show(screen_id, start_time);
CREATE INDEX idx_show_seat_show ON show_seat(show_id);
